#!/bin/sh

# LAUNCHERS
$HOME/.config/bspwm/autostart.sh

# BSPWM configuration
bspc config border_radius        5
bspc config border_width         2
bspc config window_gap           5
bspc config top_padding          5
bspc config bottom_padding       5
bspc config left_padding         5
bspc config right_padding        5

bspc config single_monocle       false
bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false 
bspc config focus_follows_pointer true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring

bspc config focused_border_color    "#d79921"
bspc config normal_border_color     "#282828"
bspc config active_border_color     "#282828"
bspc config presel_feedback_color   "#282828"
bspc config urgent_border_color     "#cc241d"
# bspc config focused_border_color	"#4c566a"
# bspc config normal_border_color		"#2e3440"
# bspc config active_border_color		"#2e3440"
# bspc config presel_feedback_color	"#88c0d0"
# bspc config urgent_border_color 	"#2e3440"

# Laptop monitor
bspc monitor eDP1 -d I II III IV V VI
# External monitor
# bspc monitor DP1 -d code web chat media other
# PC Monitor
# bspc monitor HDMI-1 -d code web chat media other
